### ISSUE TITLE
how to build it with ndk？

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [crystax/android-vendor-boost-1-60-0#1]
i download the source code， but I don't Know how to build it with ndk

**Comment by dmsck** [comment]
This is just Boost sources used within CrystaX NDK build process. You don't need rebuild it on your own unless you really need that, since prebuilt Boost libraries are already included to the CrystaX NDK. Specifically 1.60.0 is not yet included to the latest release (10.3.1), but you can download daily builds from https://dl.crystax.net/builds/ and use Boost 1.60.0 there.
